version: "3.8"
services:
  web:
    build:
      context: Angular
      dockerfile: Dockerfile
    ports:
      - "4200:80"
  service:
    build:
      context: Service
      dockerfile: Dockerfile
    ports:
      - "5000:80"
