FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["Application.csproj", "."]
RUN dotnet restore "Application.csproj"
COPY [".", "."]
RUN dotnet build "Application.csproj" -c Release -o /app/build
RUN dotnet publish "Application.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
EXPOSE 80
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Application.dll"]