version: "3.8"
services:
  web:
    build:
      context: ../Web
      dockerfile: Dockerfile.development
    ports:
      - "4200:80"
  # api:
  #   build:
  #     context: ../.
  #     dockerfile: Service/Dockerfile.development
  #   ports:
  #     - "5000:80"

