version: "3.8"
services:
  web:
    image: demo_web_${ENV}:${TAG}
    build:
      context: ../.
      dockerfile: ./.project/Dockerfile.web
      args:
        - ANGULAR_ENVIRONMENT=${ENV}
    ports:
      - 4200:80
  api:
    image: demo_service_${ENV}:${TAG}
    build:
      context: ../.
      dockerfile: ./.project/Dockerfile.service
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENV}
    ports:
      - 5000:80
