version: "3.8"
services:
  # web:
  #   build:
  #     context: ../Web
  #     dockerfile: Dockerfile.debug
  #   ports:
  #     - 4200:80
  api:
    build:
      context: ../.
      dockerfile: Service/Dockerfile
      # args:
      #   - configuration=Release
    ports:
      - 5000:80
