version: "3.8"
services:
  web:
    build:
      context: ../Angular
      dockerfile: Dockerfile.release
      args:
        release: "false"
    ports:
      - "4200:80"
  service:
    build:
      context: ../Service
      dockerfile: Dockerfile.release
      args:
        release: "false"
    ports:
      - "5000:80"

